src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
#[ORM\Table(name: '`comment`')]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $publishedAt = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isPublished = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $Author = null;

    #[ORM\ManyToOne(targetEntity: Article::class, inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Article $article = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(\DateTimeInterface $publishedAt): static
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function isIsPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setIsPublished(bool $isPublished): static
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->Author;
    }

    public function setAuthor(?User $Author): static
    {
        $this->Author = $Author;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): static
    {
        $this->article = $article;

        return $this;
    }
}

src/Controller/CommentController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\Persistence\ManagerRegistry as PersistenceManagerRegistry;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Comment;
use App\Entity\Article;

class CommentController extends AbstractController
{
    //#[Route('/recette/{articleId}/commentaire/ajout', name: 'commentaire_ajout', methods: 'POST')]
    public function ajout(PersistenceManagerRegistry $doctrine, Request $request): Response
    {
        $articleId = $request->request->get('article_id'); // Récupérer article_id depuis la page html.
        $contenu = $request->request->get('contenu'); // idem pour la zone text-area.
        $em = $doctrine->getManager();

        // Récupérer l'article correspondant à partir de son ID en BDD
        $article = $em->getRepository(Article::class)->find($articleId);

        //Vérifier si l'article existe en BDD.
        if (!$article) {
            throw $this->createNotFoundException('Article non trouvé pour l\'ID ' . $articleId);
        }

        $comments = new Comment();
        $comments->setContent($contenu); // Associer le contenu récupéré au dessus dans la variable comments.
        $comments->setArticle($article); // Associer comments à l'article correspondant via son ID.

        if(!$contenu == '')
        {
            $this->saveComment($doctrine, $comments);
        }

        return $this->redirectToRoute('article_show', ['id' => $article->getId()]);
    }

    private function completeCommentBeforeSave(Comment $comments) {
        if($comments->getPublishedAt()){
            $comments->getPublishedAt(new \DateTime());
        }
        $comments->setAuthor($this->getUser()); // Ajouter l'autheur du commentaire.
        $comments->setPublishedAt(new \DateTime()); // Ajouter la date de publication du commentaire.
    
        return $comments;
    }

    /**
     * Enregistrer un commentaire en base de données
     * 
     * @param   Comment     $comments
     */
    private function saveComment(PersistenceManagerRegistry $doctrine, Comment $comments)
    {
        $comments = $this->completeCommentBeforeSave($comments);

        $em = $doctrine->getManager();
        $em->persist($comments); // sauvegarder les modifications.
        $em->flush(); // et enregistrer en BDD.
    }
}

templates/comment/comments.html.twig
<h4 class="mt-3"> Commentaires </h4>
{% if article.comments is not empty %}
    <section class="my-2">
        <button type="button" class="btn btn-success mb-3" data-toggle="collapse" data-target="#comments-{{ article.id }}">
        <span class="far fa-comments"></span> Voir les commentaires</button>
        <div class="collapse text-left" id="comments-{{ article.id }}">
            {% for comments in article.comments %}
                <p class="rounded border border-dark bg-light col-10 col-md-8 mx-auto py-2">
                    Ajouté par 
                    <span class="badge badge-info">{{ comments.author.username }}</span>
                    le <span class="text-secondary" style="font-weight: bold">{{ comments.publishedAt | date("d-m-Y") }}</span> 
                    à <span class="text-secondary" style="font-weight: bold">{{ comments.publishedAt | date("H:i:s") }}</span></br></br>
                    <span class="fas fa-angle-right"></span> {{ comments.content }}
                </p>
            {% endfor %}
        </div>
    </section>
    {% else %}
        <p>Aucun commentaires</p>
{% endif %}

<h5 class="mt-3"> Ajouter un commentaire </h5>
<form action="{{ path('comm_add') }}" method="post">
    <textarea class="col-md-5 col-8" name="contenu"></textarea></br>
    <input type="hidden" name="article_id" value="{{ article.id }}"></input>
    <button class="rounded btn btn-sm btn-warning mb-3 text-uppercase" type="submit">Ajouter mon commentaire 
    <i class="fas fa-paper-plane"></i></button>
</form>